package moe.caffeine.fridgehero.openfoodfacts

import kotlinx.serialization.Serializable

@Serializable
data class OpenFoodFactsResponse(
    val code : String = "",
    val product : OpenFoodFactsProduct = OpenFoodFactsProduct(),
    val status : Int = 0,
    val status_verbose : String = "",
)

@Serializable
data class OpenFoodFactsProduct(
    val allergens : String = "",
    val allergens_from_ingredients : String = "",
    val allergens_hierarchy : List<String> = listOf(),
    val amino_acids_tags : List<String> = listOf(),
    val brands : String = "",
    val brands_tags : List<String> = listOf(),
    val categories : String = "",
    val categories_hierarchy : List<String> = listOf(),
    val categories_tags : List<String> = listOf(),
    val code : String = "",
    val complete : Int = 0,
    val completeness : Double = 0.0,
    val expiration_date : String = "",
    val food_groups_tags : List<String> = listOf(),
    val generic_name : String = "",
    val generic_name_en : String = "",
    val id : String = "",
    val image_front_small_url : String = "",
    val image_front_thumb_url : String = "",
    val image_front_url : String = "",
    val image_small_url : String = "",
    val image_thumb_url : String = "",
    val image_url : String = "",
    val ingredients_from_palm_oil_tags : List<String> = listOf(),
    val ingredients_text : String = "",
    val ingredients_text_en : String = "",
    val ingredients_text_with_allergens : String = "",
    val ingredients_text_with_allergens_en : String = "",
    val ingredients_that_may_be_from_palm_oil_tags : List<String> = listOf(),
    val labels : String = "",
    val labels_hierarchy : List<String> = listOf(),
    val labels_tags : List<String> = listOf(),
    val link : String = "",
    val minerals_tags : List<String> = listOf(),
    val no_nutrition_data : String = "",
    val nutriscore_grade : String = "",
    val nutriscore_tags : List<String> = listOf(),
    val nutriscore_version : String = "",
    val nutrition_data : String = "",
    val nutrition_data_per : String = "",
    val nutrition_data_prepared : String = "",
    val nutrition_data_prepared_per : String = "",
    val nutrition_grade_fr : String = "",
    val nutrition_grades : String = "",
    val nutrition_grades_tags : List<String> = listOf(),
    val nutrition_score_beverage : Int = 0,
    val nutrition_score_debug : String = "",
    val nutrition_score_warning_no_fiber : Int = 0,
    val nutrition_score_warning_no_fruits_vegetables_nuts : Int = 0,
    val other_nutritional_substances_tags : List<String> = listOf(),
    val packaging : String = "",
    val packaging_hierarchy : List<String> = listOf(),
    val packaging_materials_tags : List<String> = listOf(),
    val packaging_recycling_tags : List<String> = listOf(),
    val packaging_shapes_tags : List<String> = listOf(),
    val packaging_tags : List<String> = listOf(),
    val packaging_text : String = "",
    val packaging_text_en : String = "",
    val product_name : String = "",
    val product_name_en : String = "",
    val quantity : String = "",
    val vitamins_tags : List<String> = listOf(),
)